{
 "title": "Public Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Self Hosted Runners",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "total number",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(os, status, instance) (self_hosted_runners{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Status: All",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(os, instance) (self_hosted_runners{organization=\"github-insights\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "total number",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum without(os, instance) (self_hosted_runners{organization=\"github-insights\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Current OS Distribution",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(status, instance) (self_hosted_runners{organization=\"github-insights\"})",
       "legendFormat": "{{os}}"
      }
     ]
    },
    {
     "title": "OS Distribution Over Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
     "targets": [
      {
       "expr": "sum without(status, job, instance) (self_hosted_runners{organization=\"github-insights\"})",
       "legendFormat": "{{os}}"
      }
     ]
    },
    {
     "title": "Current Status: Mac OS",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(os, instance) (self_hosted_runners{organization=\"github-insights\", os=\"MAC_OS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Current Status: Linux",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(os, instance) (self_hosted_runners{organization=\"github-insights\", os=\"LINUX\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Current Status: Windows",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(os, instance) (self_hosted_runners{organization=\"github-insights\", os=\"WINDOWS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repositories Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (repositories_count{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Repositories Count Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "sum without (instance) (repositories_count{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate Limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Headers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_limit{organization=\"github-insights\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum without(instance) (api_ratelimit_state_used{organization=\"github-insights\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum without(instance) (api_ratelimit_state_remaining{organization=\"github-insights\"})",
       "legendFormat": "Remaining"
      }
     ]
    },
    {
     "title": "Reset Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_reset{organization=\"github-insights\"} * 1000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests made over time (from headers)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_used{organization=\"github-insights\"})",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Actual compared to Ideal req/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 98 },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_actual_req{organization=\"github-insights\"})",
       "legendFormat": "Actual"
      },
      {
       "expr": "sum without(instance) (api_ratelimit_state_ideal_req{organization=\"github-insights\"})",
       "legendFormat": "Ideal"
      }
     ]
    },
    {
     "title": "Current Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_status{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status Over Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 102 },
     "targets": [
      {
       "expr": "sum without(instance) (api_ratelimit_state_status{organization=\"github-insights\"})",
       "legendFormat": "status over time"
      }
     ]
    },
    {
     "title": "Summed Requests from all Clients",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum without(uri, method, error, status, instance) (http_client_requests_seconds_count{organization=\"github-insights\"})",
       "legendFormat": "summed requests"
      }
     ]
    },
    {
     "title": "Summed Requests from all Clients",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 10, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(uri, method, status, error, instance) (http_client_requests_seconds_count{organization=\"github-insights\"})",
       "legendFormat": "{{summed requests}}"
      }
     ]
    },
    {
     "title": "Share of requests by endpoint",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance, method, status, job, error) (http_client_requests_seconds_count{organization=\"github-insights\"})",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "summed 2xx responses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(method, uri, error, instance) (http_client_requests_seconds_count{organization=\"github-insights\", status=\"2xx\"})",
       "legendFormat": "{{summed requests}}"
      }
     ]
    },
    {
     "title": "summed 4xx responses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(method, uri, instance) (http_client_requests_seconds_count{organization=\"github-insights\", status=\"4xx\"})",
       "legendFormat": "{{summed requests}}"
      }
     ]
    },
    {
     "title": "exeptions encountered",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(method, uri, status, error, instance) (http_client_requests_seconds_count{organization=\"github-insights\", error!=\"none\"})",
       "legendFormat": "{{summed requests}}"
      }
     ]
    },
    {
     "title": "list of exeptions encountered",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(method, uri, instance) (http_client_requests_seconds_count{organization=\"github-insights\", error!=\"none\"})",
       "legendFormat": "{{error}} - {{status}}"
      }
     ]
    },
    {
     "title": "Number of requests by endpoint",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 126 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(error, status, method, instance) (http_client_requests_seconds_count{organization=\"$organization\"})",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Runs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently active",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(status, instance) (active_workflow_runs{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "In The Last 24 Hours",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(status, instance, organization, job) (workflow_runs{organization=~\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance) (workflow_runs{organization=\"github-insights\", status=~\"FAILED|DONE|ACTION_REQUIRED\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Status Pie",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance) (workflow_runs{organization=\"github-insights\",status=~\"DONE|ACTION_REQUIRED|FAILED\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 114 },
     "targets": [
      {
       "expr": "sum without(instance) (workflow_runs{organization=\"github-insights\", status=~\"DONE|FAILED|ACTION_REQUIRED\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Average Workflow Run Build Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "expr": "sum without(instance, status, job) (workflow_runs_average_build_times{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Workflow Run Build Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "sum without(instance, status, job) (workflow_runs_total_build_times{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Workflow Runs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Workflow Runs Over Time Stacked",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "sum without (instance) (active_workflow_runs{organization=\"github-insights\",status=~\"PENDING|IN_PROGRESS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Active Workflow Runs Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "targets": [
      {
       "expr": "sum without (instance) (active_workflow_runs{organization=\"github-insights\",status=~\"PENDING|IN_PROGRESS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Current Active Workflow Runs Over Time (Bar)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (active_workflow_runs{organization=\"github-insights\",status=~\"PENDING|IN_PROGRESS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Current Active Workflow Runs Over Time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (active_workflow_runs{organization=\"github-insights\",status=~\"PENDING|IN_PROGRESS\"})",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Run Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Conclusions in the Last 24 Hours Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum without(instance, status) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{conclusion}}"
      }
     ]
    },
    {
     "title": "Job Status's in the Last 24 Hours Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum without(instance, conclusion) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "In the last 24 Hours",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 101 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(status, conclusion, instance) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 101 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance, conclusion) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "status distribution",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance, conclusion) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "conclusion distribution",
     "type": "stat",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance, status) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{conclusion}}"
      }
     ]
    },
    {
     "title": "conclusion distribution",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without(instance, status) (workflow_run_jobs{organization=\"github-insights\"})",
       "legendFormat": "{{conclusion}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Run Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Workflow Run Build Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum without(instance, status, job) (workflow_runs_average_build_times{organization=\"github-insights\"}) /1000/60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Workflow Run Build Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum without(instance, status, job) (workflow_runs_total_build_times{organization=\"github-insights\"}) /1000/60",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Pull Request States of last day",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (pull_requests_count_of_last_1_days{organization=\"github-insights\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Current Pull Request States of last 7 days",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (pull_requests_count_of_last_7_days{organization=\"github-insights\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Current Pull Request States of last day",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (pull_requests_count_of_last_1_days{organization=\"github-insights\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Current Pull Request States of last 7 days",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (pull_requests_count_of_last_7_days{organization=\"github-insights\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Pull Requests per day over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum without (instance) (pull_requests_count_of_last_1_days{organization=\"github-insights\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Pull Request Throughput over the last 7 days",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum without (instance) (pull_request_throughput_of_last_7_days{organization=\"github-insights\"})",
       "legendFormat": "Merged PRs"
      }
     ]
    }
   ]
  }
 ]
}